### ISSUE TITLE
How to specify folder at runtime?

### ISSUE THREAD

**Issue by DuredhelFinceleb** [pyros2097/rust-embed#158]
I'm using 'clap' to pass at runtime an arg telling my program where is the folder to embed.
Let's say I get it in a var called 'my_folder_path'
How do I pass it to rust-embed?
Doing this:
```
#[derive(RustEmbed)]
#[folder = my_folder_path]
```
does not work obviously since my var does not even exist yet

New to Rust, sorry if this is a stupid question.

I'm using rust-embed to produce binaries with embedded static websites that I can run anywhere even on machines with no dev tooling so it would be nice to be able to avoid having to edit the source code everytime I want to embed a different set of files.

Well the best would be to be able to create a program that would pick up a source code & a folder and compile a new program running that code with the embedded file
I can do this in Deno with Leaf but in Rust this is way above my current level I'm afraid

**Comment by AzureMarker** [comment]
Just so I understand your use case, you want to run a program that will compile a second program, and the first program decides what folder the second program embeds? Can you share the working Deno project?

Otherwise, this does not make sense: "pass at runtime an arg telling my program where is the folder to embed". Embedding happens at compile time, not runtime.

The [`interpolate-folder-path`](https://github.com/pyros2097/rust-embed#interpolate-folder-path) feature can be used to set the embedded folder path based on environment variables. This, combined with a [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) could be used to programmatically change the path to be embedded when you compile your program (by [setting an environment variable](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-env)).

**Comment by DuredhelFinceleb** [comment]
Here is the Deno project: https://github.com/DuredhelFinceleb/embedded_files_server_deno

Looking at it again in regard to the interpolate-folder-path feature, it becomes much clearer.
I understand what I need to do to get what I want, I think it's even simpler than in Deno.

Btw, the Rust project is here: https://github.com/DuredhelFinceleb/embedded_files_server
I'm gonna update it to use the interpolate-folder-path feature

**Comment by AzureMarker** [comment]
Looks good, though I would suggest not using a shell script to build (just tell the user to set an env variable and run `cargo build`).

Another reason you might want to use a (Rust) build script is to automatically recompile if the environment variable changes. This can be done via [`rerun-if-env-changed`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-env-changed). Also, you could fail the build if the environment variable is not set.

**Comment by AzureMarker** [comment]
Closing this for now since I think the question is answered. But feel free to continue discussing if you want.

**Comment by DuredhelFinceleb** [comment]
Yeah  can be closed.
Followed your suggestion and project know use the idomatic Rust way to do this
Thanks a lot! 😃
